
const listCounties = () => {return {
    general: "Clasament național",
    B: "București", 
    AB: "Alba",
    AR: "Arad",
    AG: "Argeș",
    BC: "Bacău",
    BH: "Bihor",
    BN: "Bistrița-Năsăud",
    BT: "Botoșani",
    BR: "Brăila",
    BV: "Brașov",
    BZ: "Buzău",
    CL: "Călărași",
    CS: "Caraș-Severin",
    CJ: "Cluj",
    CT: "Constanța",
    CV: "Covasna",
    DB: "Dâmbovița",
    DJ: "Dolj",
    GL: "Galati",
    GR: "Giurgiu",
    GJ: "Gorj",
    HT: "Harghita",
    HD: "Hunedoara",
    IL: "Ialomița",
    IS: "Iași",
    IF: "Ilfov",
    MM: "Maramureș",
    MH: "Mehedinți",
    MS: "Mureș",
    NT: "Neamț",
    OT: "Olt",
    PH: "Prahova",
    SJ: "Sălaj",
    SM: "Satu Mare",
    SB: "Sibiu",
    SV: "Suceava",
    TR: "Teleorman",
    TM: "Timiș",
    TL: "Tulcea",
    VL: "Valcea",
    VS: "Vaslui",
    VN: "Vrancea"
};
}

export default listCounties;